### ISSUE TITLE
case-sensitive paths on a case-insensitive filesystem

### ISSUE THREAD

**Issue by peersky** [bugout-dev/dao#2]
### Problem

Cloning repo on Mac OS produces warning
```
git clone git@github.com:bugout-dev/dao.git
Cloning into 'dao'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 74 (delta 27), reused 66 (delta 24), pack-reused 0
Receiving objects: 100% (74/74), 24.73 KiB | 6.18 MiB/s, done.
Resolving deltas: 100% (27/27), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'dao/Diamond.py'
  'dao/diamond.py'
```

reason is that OSX is not case sensitive.

### Solution

It is okey to use Upper/Lower case letters in file names as long as their name translation to lower case does not produces a duplicate file.

**Comment by zomglings** [comment]
OS X and Windows both use case insensitive filesystems by default, so it is important for us to fix this.

My suggestion is to use the `dao/contracts` directory to store the generated files (e.g. `Diamond.py`, `DiamondLoupeFacet.py`, etc.).
